import { Venue } from '../types';

export const mockVenues: Venue[] = [
  {
    id: '1',
    name: 'Skybar Rooftop',
    address: 'Midtown Manhattan, NY',
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400',
    priceRange: '$$$',
    category: 'Rooftop',
    description: 'Stunning rooftop bar with panoramic city views and premium cocktails.',
    capacity: 150,
    minSpend: 450,
    features: ['Rooftop Terrace', 'City Views', 'Premium Bar', 'VIP Tables'],
    openHours: '6:00 PM - 2:00 AM',
    dresscode: 'Upscale Casual',
  },
  {
    id: '2',
    name: 'Neon Nightclub',
    address: 'Downtown District, NY',
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1571266028243-d220c9c3814b?w=400',
    priceRange: '$$$$',
    category: 'Club',
    description: 'High-energy nightclub with world-class DJs and state-of-the-art sound.',
    capacity: 300,
    minSpend: 680,
    features: ['Live DJs', 'Dance Floor', 'VIP Booths', 'Premium Sound'],
    openHours: '10:00 PM - 4:00 AM',
    dresscode: 'Trendy/Fashionable',
  },
  {
    id: '3',
    name: 'Velvet Lounge',
    address: 'Upper East Side, NY',
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400',
    priceRange: '$$$',
    category: 'Lounge',
    description: 'Sophisticated lounge with craft cocktails and intimate ambiance.',
    capacity: 80,
    minSpend: 320,
    features: ['Craft Cocktails', 'Intimate Setting', 'Live Music', 'Private Booths'],
    openHours: '7:00 PM - 1:00 AM',
    dresscode: 'Business Casual',
  },
  {
    id: '4',
    name: 'Apex Club',
    address: 'Chelsea, NY',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a8b?w=400',
    priceRange: '$$$$',
    category: 'Club',
    description: 'Exclusive club featuring celebrity DJs and ultra-premium service.',
    capacity: 200,
    minSpend: 850,
    features: ['Celebrity DJs', 'VIP Service', 'Bottle Service', 'Private Rooms'],
    openHours: '11:00 PM - 5:00 AM',
    dresscode: 'Formal/Designer',
  },
  {
    id: '5',
    name: 'Pool & Sky',
    address: 'Brooklyn Heights, NY',
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1544537150-6e4c999de2a0?w=400',
    priceRange: '$$',
    category: 'Pool Party',
    description: 'Outdoor pool party venue with summer vibes and refreshing cocktails.',
    capacity: 120,
    minSpend: 280,
    features: ['Outdoor Pool', 'Summer Vibes', 'Cabanas', 'Poolside Bar'],
    openHours: '2:00 PM - 10:00 PM',
    dresscode: 'Resort Casual',
  },
  {
    id: '6',
    name: 'The Underground',
    address: 'Lower East Side, NY',
    rating: 4.4,
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400',
    priceRange: '$$',
    category: 'Club',
    description: 'Underground club with edgy atmosphere and alternative music scene.',
    capacity: 180,
    minSpend: 350,
    features: ['Underground Vibe', 'Alternative Music', 'Unique Atmosphere', 'Local DJs'],
    openHours: '9:00 PM - 3:00 AM',
    dresscode: 'Casual/Edgy',
  },
];

export const venueCategories = [
  'All',
  'Rooftop',
  'Lounge', 
  'Club',
  'Pool Party',
];

export const priceRanges = [
  { label: 'Any Price', value: 'any' },
  { label: '$$ ($200-400)', value: '$$' },
  { label: '$$$ ($400-600)', value: '$$$' },
  { label: '$$$$ ($600+)', value: '$$$$' },
]; 